Implémentation d'une API HTTP de style REST pour Apache OFBiz
=============================================================
Mathieu Lirzin <mathieu.lirzin@nereide.fr>

:numbered!:
== Introduction
Dans le cadre d'une amélioration du progiciel de gestion intégré Apache OFBiz nous souhaitons mettre en place une API HTTP basée sur lestyle d'architecture REST pour les échanges entre les différents
composants logiciels de type service. Il sera demandé au stagiaire dans un premier temps de réaliser un état de l'art de l'utilisation de ce style architectural, puis d'étudier les principes d'architectures orientées services (SOA) utilisés dans le framework Apache OFBiz.

Après cette phase d'analyse, l'API HTTP basée sur le style REST devra être implementée dans le framework Apache OFBiz en suivant les principes SOA.
Ces améliorations devront être réalisées en interaction avec les projets clients et la communauté Apache OFBiz afin de permettre leurs intégration dans le projet officiel.

:numbered:
== État de l'art

=== Architecture REST

_Representational State Transfer_ (REST) est un style architectural décrit par Roy Fielding dans sa thèse de doctorat <<fielding2000architectural>> dont l'idée principale est la communication « *stateless* » au travers de la notion de ressources accessibles au moyen d'un nombre réduit d'actions.
Ces ressources sont liées entre elles par des liens Hypertextes sensé permettre leur découvrabilité.
La découvrabilité des ressources est décrite par le principe _Hypermedia As The Engine Of Application State_ (HATEOAS).

["graphviz"]
------------
digraph G {
  layout=dot
  node [shape=box, style=rounded];
  rankdir="LR";
  splines=spline;


  subgraph cluster_client {
    rank=min;
    client [shape=egg];
  }

  subgraph cluster_api {
    style=dashed
    label="API";
    id1;
    id2;
    id3;
    id4;
    color=grey
    rank=same;
  }

  subgraph cluster_ressources {
    data1;
    data2;
    data3;
    label = "ressources";
    color=blue;
    rank=max
  }

  client -> id1 [label="GET", style=dotted];
  client -> id3 [label="POST", style=dotted];
  client -> id4 [label="POST", style=dotted];
  id1 -> { data1 data2 data3 };
  id2 -> data2;
  id3 -> data2;
  id4 -> data3;
  nodesep=0.25
  ranksep=0.8
}
----

// Liens donnés par Nicolas
//
// * https://www.infoq.com/articles/rest-introduction
// * http://apidoc.adility.com/submission-api
// * https://issues.apache.org/jira/browse/OFBIZ-4274
// * http://blog.pilotsystems.net/2012/septembre/les-api-rest

==== Protocole HTTP

Le protocole HTTP est un protocole texte utilisé sur le Web pour transmettre les ressources HTML, CSS, Javascript.
Ce protocole suit les contraintes définies par le style architectural REST.
L'accès aux ressources se fait au moyen de 4 méthodes principales `GET`, `POST`, `HEAD`, `DELETE` mais également de 5 autres méthodes moins courantes `OPTIONS`, `CONNECT`, `TRACE`, `PUT`, `PATCH`.

La standardisation des types de méthodes permettent à des clients génériques de faire des suppositions sur le propriétés de ces méthodes.
Par exemple de la méthode `GET` est nullpotent c'est à dire qu'elle ne doit pas modifier l'état des ressources, et la méthode `POST` est idempotent c'est à dire que la réception de plusieurs message ne doit produire qu'une seule action.

l'URI ne doit pas être l'API mais la représentation des données identifié par cette URI.
En pratique cela qu'il faut privélégier la récupération d'URL dans les payloads plutôt que concaténer des chaînes de caractères qui est un signe que l'URL est l'API.
//Comment traiter le versioning?

==== Format de données

Lors d'une requête, il est possible pour le client de spécifier le type contenu souhaité au moyen du header `Accept` cependant il faut que le serveur recevant cette requête soit en mesure de fournir le format de donnée souhaité.
Dans la pratique les formats XML est JSON sont les plus courant pour la transmission de données structurées.

:numbered!:
[bibliography]
== Bibliography

[bibliography]
- [[[fielding2000architectural]]] Roy Fielding. 'Architectural styles and the design of network-based software architectures'. Addison-Wesley. University of California, Irvine Doctoral dissertation . 2000
// https://www.ics.uci.edu/~fielding/pubs/dissertation/fielding_dissertation.pdf

- [[[rfc2616]]] Roy Fielding, Jim Gettys, Jeffrey Mogul, et al. 'Hypertext transfer protocol--HTTP/1.1' . 1999

- [[[modern-web-archi]]] Roy Fielding et Richard Taylor 'Principled design of the modern Web architecture'. ACM Transactions on Internet Technology (TOIT), 2002, vol. 2, no 2, p. 115-150.

- [[[rest-misconception]]] Stefan Tilkov 'REST: I don't Think it Means What You Think it Does' https://www.infoq.com/presentations/rest-misconceptions Mars 2015.  visité le 05/04/2018.
