= Implémentation d'une API HTTP de style REST pour Apache OFBiz
Mathieu Lirzin <mathieu.lirzin@nereide.fr>

:numbered!:
== Introduction
Dans le cadre d'une amélioration du progiciel de gestion intégré Apache OFBiz nous souhaitons mettre en place une API HTTP basée sur lestyle d'architecture REST pour les échanges entre les différents
composants logiciels de type service. Il sera demandé au stagiaire dans un premier temps de réaliser un état de l'art de l'utilisation de ce style architectural, puis d'étudier les principes d'architectures orientées services (SOA) utilisés dans le framework Apache OFBiz.

Après cette phase d'analyse, l'API HTTP basée sur le style REST devra être implementée dans le framework Apache OFBiz en suivant les principes SOA.
Ces améliorations devront être réalisées en interaction avec les projets clients et la communauté Apache OFBiz afin de permettre leurs intégration dans le projet officiel.

:numbered:
== État de l'art

=== Architecture REST

Liens donnés par Nicolas

* https://www.infoq.com/articles/rest-introduction
* http://apidoc.adility.com/submission-api
* https://issues.apache.org/jira/browse/OFBIZ-4274
* http://blog.pilotsystems.net/2012/septembre/les-api-rest

Thèse de Roy Fielding <<fielding2000architectural>>

:numbered!:
[bibliography]
== Bibliography

[bibliography]
- [[[fielding2000architectural]]] Roy Fielding. 'Architectural styles and the design of network-based software architectures'. Addison-Wesley. University of California, Irvine Doctoral dissertation . 2000
